[package]
name = "nive-runtime"
version = "0.1.0-alpha.1"
edition = "2021"
rust-version = "1.92"
license = "Apache-2.0"
description = "Reusable runtime foundation for Rust/Iced desktop applications."
repository = "https://github.com/JirlanSouza/nive"
documentation = "https://docs.rs/nive-runtime"
readme = "README.md"
keywords = ["gui", "desktop", "iced", "runtime"]
categories = ["gui"]

[lints]
workspace = true

[features]
default = []
file-picker = ["dep:rfd"]
devtools = ["nive-runtime-derive/devtools"]

[dependencies]
iced = { workspace = true }
log = { workspace = true }
nive-core = { version = "0.1.0-alpha.1", path = "../nive-core" }
nive-runtime-derive = { version = "0.1.0-alpha.1", path = "../nive-runtime-derive" }
nive-ui = { version = "0.1.0-alpha.1", path = "../nive-ui" }
rfd = { version = "0.16", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
iced_renderer = "0.14"
iced_runtime = "0.14"
iced_tiny_skia = "0.14"
tempfile = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSApplication", "NSImage", "NSResponder"] }
objc2-foundation = { version = "0.3", default-features = false, features = ["std", "NSData"] }
