// Bundled icons are sourced from Lucide (https://lucide.dev) and distributed under the ISC License.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconName {
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Close,
    Copy,
    Edit,
    Eye,
    EyeOff,
    Folder,
    Inbox,
    Info,
    Menu,
    Minus,
    MoreHorizontal,
    Plus,
    RefreshCw,
    Search,
    Settings,
    Trash,
}

impl IconSource for IconName {
    fn svg_bytes(self) -> &'static [u8] {
        match self {
            Self::AlertCircle => include_bytes!("../../assets/icons/lucide/circle-alert.svg"),
            Self::AlertTriangle => include_bytes!("../../assets/icons/lucide/triangle-alert.svg"),
            Self::ArrowLeft => include_bytes!("../../assets/icons/lucide/arrow-left.svg"),
            Self::ArrowRight => include_bytes!("../../assets/icons/lucide/arrow-right.svg"),
            Self::Check => include_bytes!("../../assets/icons/lucide/check.svg"),
            Self::CheckCircle => include_bytes!("../../assets/icons/lucide/circle-check.svg"),
            Self::ChevronDown => include_bytes!("../../assets/icons/lucide/chevron-down.svg"),
            Self::ChevronLeft => include_bytes!("../../assets/icons/lucide/chevron-left.svg"),
            Self::ChevronRight => include_bytes!("../../assets/icons/lucide/chevron-right.svg"),
            Self::ChevronUp => include_bytes!("../../assets/icons/lucide/chevron-up.svg"),
            Self::Close => include_bytes!("../../assets/icons/lucide/x.svg"),
            Self::Copy => include_bytes!("../../assets/icons/lucide/copy.svg"),
            Self::Edit => include_bytes!("../../assets/icons/lucide/pencil.svg"),
            Self::Eye => include_bytes!("../../assets/icons/lucide/eye.svg"),
            Self::EyeOff => include_bytes!("../../assets/icons/lucide/eye-off.svg"),
            Self::Folder => include_bytes!("../../assets/icons/lucide/folder.svg"),
            Self::Inbox => include_bytes!("../../assets/icons/lucide/inbox.svg"),
            Self::Info => include_bytes!("../../assets/icons/lucide/info.svg"),
            Self::Menu => include_bytes!("../../assets/icons/lucide/menu.svg"),
            Self::Minus => include_bytes!("../../assets/icons/lucide/minus.svg"),
            Self::MoreHorizontal => include_bytes!("../../assets/icons/lucide/ellipsis.svg"),
            Self::Plus => include_bytes!("../../assets/icons/lucide/plus.svg"),
            Self::RefreshCw => include_bytes!("../../assets/icons/lucide/refresh-cw.svg"),
            Self::Search => include_bytes!("../../assets/icons/lucide/search.svg"),
            Self::Settings => include_bytes!("../../assets/icons/lucide/settings.svg"),
            Self::Trash => include_bytes!("../../assets/icons/lucide/trash.svg"),
        }
    }

    fn provider_slug(self) -> &'static str {
        match self {
            Self::AlertCircle => "circle-alert",
            Self::AlertTriangle => "triangle-alert",
            Self::ArrowLeft => "arrow-left",
            Self::ArrowRight => "arrow-right",
            Self::Check => "check",
            Self::CheckCircle => "circle-check",
            Self::ChevronDown => "chevron-down",
            Self::ChevronLeft => "chevron-left",
            Self::ChevronRight => "chevron-right",
            Self::ChevronUp => "chevron-up",
            Self::Close => "x",
            Self::Copy => "copy",
            Self::Edit => "pencil",
            Self::Eye => "eye",
            Self::EyeOff => "eye-off",
            Self::Folder => "folder",
            Self::Inbox => "inbox",
            Self::Info => "info",
            Self::Menu => "menu",
            Self::Minus => "minus",
            Self::MoreHorizontal => "ellipsis",
            Self::Plus => "plus",
            Self::RefreshCw => "refresh-cw",
            Self::Search => "search",
            Self::Settings => "settings",
            Self::Trash => "trash",
        }
    }
}
