[workspace]
members = [
  "crates/nive-core",
  "crates/nive-ui",
  "crates/nive-runtime",
  "crates/nive-runtime-derive",
  "crates/nive-workbench",
  "crates/nive",
  "crates/nive-cli",
]
resolver = "2"

[workspace.dependencies]
futures = "0.3"
log = "0.4"
serde = "1"
serde_json = "1"
tempfile = "3"
thiserror = "1"
time = "0.3"
tokio = "1"
iced = { version = "0.14", features = ["tokio", "svg", "advanced", "canvas"] }
toml = "0.8.2"
toml_edit = "0.22"
clap = { version = "4", features = ["derive"] }
include_dir = "0.7"
unicode-segmentation = "1"

[workspace.lints.clippy]
mod_module_files = "warn"
wildcard_imports = "warn"
