[package]
name = "nive-cli"
version = "0.1.0-alpha.1"
edition = "2021"
rust-version = "1.92"
license = "Apache-2.0"
description = "CLI for scaffolding and icon management in Nive apps."
repository = "https://github.com/JirlanSouza/nive"
documentation = "https://docs.rs/nive-cli"
readme = "README.md"
keywords = ["gui", "desktop", "iced", "cli"]
categories = ["gui", "command-line-utilities"]

[lints]
workspace = true

[[bin]]
name = "nive"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
flate2 = "1"
include_dir = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tar = "0.4"
toml = { workspace = true }
toml_edit = { workspace = true }
ureq = "3"

[dev-dependencies]
tempfile = { workspace = true }
